using System.Text;

namespace Lox.Generator;

public static class Generator
{
    private const string AutoGenerated = 
        """
        //<auto-generated>
        // This code was generated by Tool. Any changes will be erased.
        //</auto-generated>
        
        """;
    
    /// <summary>
    /// Generates .cs files needed for AST
    /// </summary>
    /// <param name="outputDir">Root directory where each cs file will be stored</param>
    /// <param name="nameSpace">C# Namespace for each file</param>
    /// <param name="interfaceName">Name of the Interface</param>
    /// <param name="types">List of types implementing the Interface</param>
    public static async Task DefineAstAsync(string outputDir, string nameSpace, string interfaceName, List<string> types)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoGenerated);
        sb.AppendLine($"namespace {nameSpace};");
        sb.AppendLine();
        sb.AppendLine($"public interface {interfaceName} {{}}");

        var interfacePath = Path.Combine(outputDir, interfaceName) + ".cs";
        await File.WriteAllTextAsync(interfacePath, sb.ToString());
        
        await DefineVisitorAsync(outputDir, nameSpace, interfaceName, types);

        foreach (var type in types)
        {
            var entry = type.Split(":");
            var className = entry[0].Trim();
            var fields = entry[1].Trim();

            await DefineTypeAsync(outputDir, nameSpace, interfaceName, className, fields);
        }
    }
    
    public static async Task DefineVisitorAsync(string outputDir, string nameSpace, string interfaceName, List<string> types)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoGenerated);
        
        sb.AppendLine($"namespace {nameSpace};");
        sb.AppendLine();
        
        sb.AppendLine("public interface IVisitor<T>");
        sb.AppendLine("{");

        foreach (var type in types)
        {
            var typeName = type.Split(":")[0].Trim();
            sb.AppendLine($"\tT Visit{typeName}({typeName} expression);");
        }

        sb.AppendLine("}");
        
        var interfacePath = Path.Combine(outputDir, "IVisitor") + ".cs";
        await File.WriteAllTextAsync(interfacePath, sb.ToString());
    }
    
    public static async Task DefineTypeAsync(string outputDir, string nameSpace, string interfaceName, string className, string fieldList)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoGenerated);
        
        sb.AppendLine($"namespace {nameSpace};");
        sb.AppendLine();
        
        sb.AppendLine($"public class {className}({fieldList}) : {interfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"\tT Accept<T>(IVisitor<T> visitor) => visitor.Visit{className}(this);");
        sb.AppendLine("}");
        
        var classPath = Path.Combine(outputDir, className) + ".cs";
        await File.WriteAllTextAsync(classPath, sb.ToString());
    }
}