using System.Text;

namespace Lox.Generator;

public static class Generator
{
    private const string AutoGenerated = 
        """
        //<auto-generated>
        // This code was generated by Tool. Any changes will be erased.
        //</auto-generated>
        
        """;
    
    /// <summary>
    /// Generates .cs files needed for AST
    /// </summary>
    /// <param name="outputDir">Root directory where each cs file will be stored</param>
    /// <param name="nameSpace">C# Namespace for each file</param>
    /// <param name="interfaceName">Name of the Interface</param>
    /// <param name="types">List of types implementing the Interface</param>
    /// <param name="nameSpacesToImport">List of namespaces to add using</param>
    public static async Task DefineAstAsync(string outputDir, string nameSpace, string interfaceName, List<string> types, List<string> nameSpacesToImport)
    {
        var dir = nameSpace.Split(".").Last();
        
        var sb = new StringBuilder();
        sb.AppendLine(AutoGenerated);

        foreach (var nsImport in nameSpacesToImport)
        {
            sb.AppendLine($"using {nsImport};");
        }
        sb.AppendLine();
        
        sb.AppendLine($"namespace {nameSpace};");
        sb.AppendLine();
        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"\tpublic T Accept<T>(I{dir}Visitor<T> visitor);");
        sb.AppendLine("}");

        var interfacePath = Path.Combine(outputDir, dir, interfaceName) + ".cs";
        
        var dirPath = Path.GetDirectoryName(interfacePath);
        if (!string.IsNullOrEmpty(dirPath))
        {
            Directory.CreateDirectory(dirPath);
        }
        
        await File.WriteAllTextAsync(interfacePath, sb.ToString());
        
        await DefineVisitorAsync(outputDir, nameSpace, interfaceName, types, nameSpacesToImport);

        foreach (var type in types)
        {
            var entry = type.Split(":");
            var className = entry[0].Trim();
            var fields = entry[1].Trim();

            await DefineTypeAsync(outputDir, nameSpace, interfaceName, className, fields, nameSpacesToImport);
        }
    }
    
    public static async Task DefineVisitorAsync(string outputDir, string nameSpace, string interfaceName, List<string> types, List<string> nameSpacesToImport)
    {
        var dir = nameSpace.Split(".").Last();
        
        var sb = new StringBuilder();
        sb.AppendLine(AutoGenerated);
        
        foreach (var nsImport in nameSpacesToImport)
        {
            sb.AppendLine($"using {nsImport};");
        }
        
        sb.AppendLine($"namespace {nameSpace};");
        sb.AppendLine();
        
        sb.AppendLine($"public interface I{dir}Visitor<T>");
        sb.AppendLine("{");

        var paramName = interfaceName.Substring(1, interfaceName.Length - 1).ToLower();
        var paramNameCapital = string.Concat(paramName[0].ToString().ToUpper(), paramName.AsSpan(1));
        
        foreach (var type in types)
        {
            var typeName = type.Split(":")[0].Trim();
            sb.AppendLine($"\tT Visit{typeName}{paramNameCapital}({typeName} {paramName});");
        }
        sb.AppendLine();

        sb.AppendLine("}");
        
        var interfacePath = Path.Combine(outputDir, dir, $"I{dir}Visitor") + ".cs";
        await File.WriteAllTextAsync(interfacePath, sb.ToString());
    }
    
    public static async Task DefineTypeAsync(string outputDir, string nameSpace, string interfaceName, string className, string fieldList, List<string> nameSpacesToImport)
    {
        var dir = nameSpace.Split(".").Last();
        
        var sb = new StringBuilder();
        sb.AppendLine(AutoGenerated);
        
        foreach (var nsImport in nameSpacesToImport)
        {
            sb.AppendLine($"using {nsImport};");
        }
        sb.AppendLine();
        
        sb.AppendLine($"namespace {nameSpace};");
        sb.AppendLine();
        
        sb.AppendLine($"public class {className}({fieldList}) : {interfaceName}");
        sb.AppendLine("{");
        var fields = fieldList.Split(", ");
        foreach (var field in fields)
        {
            var split = field.Split(" ");

            var fieldType = split[0].Trim();
            if (split.Length == 1)
                continue;

            var fieldName = split[1].Trim();
            var prop = fieldName[0].ToString().ToUpper() + fieldName.Substring(1, fieldName.Length-1);
            sb.AppendLine($"\tpublic {fieldType} {prop} => {fieldName};");
        }
        
        var paramName = interfaceName.Substring(1, interfaceName.Length - 1).ToLower();
        var paramNameCapital = string.Concat(paramName[0].ToString().ToUpper(), paramName.AsSpan(1));
        
        sb.AppendLine($"\tpublic T Accept<T>(I{dir}Visitor<T> visitor) => visitor.Visit{className}{paramNameCapital}(this);");
        sb.AppendLine("}");
        
        var classPath = Path.Combine(outputDir, dir, className) + ".cs";
        await File.WriteAllTextAsync(classPath, sb.ToString());
    }
}