//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public class Block(List<IStatement> statements) : IStatement
{
	public List<IStatement> Statements => statements;
	public T Accept<T>(IStatementVisitor<T> visitor) => visitor.VisitBlockStatement(this);
}
