//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public class Class(Token name, Variable superClass, List<Function> methods) : IStatement
{
	public Token Name => name;
	public Variable SuperClass => superClass;
	public List<Function> Methods => methods;
	public T Accept<T>(IStatementVisitor<T> visitor) => visitor.VisitClassStatement(this);
}
