//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public class Function(Token name, List<Token> parameters, List<IStatement> body) : IStatement
{
	public Token Name => name;
	public List<Token> Parameters => parameters;
	public List<IStatement> Body => body;
	public T Accept<T>(IStatementVisitor<T> visitor) => visitor.VisitFunctionStatement(this);
}
