//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public class If(IExpression condition, IStatement thenBranch, IStatement elseBranch) : IStatement
{
	public IExpression Condition => condition;
	public IStatement ThenBranch => thenBranch;
	public IStatement ElseBranch => elseBranch;
	public T Accept<T>(IStatementVisitor<T> visitor) => visitor.VisitIf(this);
}
