//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;
namespace Lox.NET.Statement;

public interface IStatementVisitor<T>
{
	T VisitStatementStatement(Statement statement);
	T VisitBlockStatement(Block statement);
	T VisitClassStatement(Class statement);
	T VisitFunctionStatement(Function statement);
	T VisitIfStatement(If statement);
	T VisitPrintStatement(Print statement);
	T VisitVarStatement(Var statement);
	T VisitWhileStatement(While statement);
	T VisitReturnStatement(Return statement);
	T VisitBreakStatement(Break statement);
	T VisitContinueStatement(Continue statement);

}
