//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public interface IStatement
{
	public T Accept<T>(IStatementVisitor<T> visitor);
}
