//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;
namespace Lox.NET.Statement;

public interface IStatementVisitor<T>
{
	T VisitStatement(Statement expression);
	T VisitBlock(Block expression);
	T VisitFunction(Function expression);
	T VisitIf(If expression);
	T VisitPrint(Print expression);
	T VisitVar(Var expression);
	T VisitWhile(While expression);
	T VisitReturn(Return expression);
	T VisitBreak(Break expression);
	T VisitContinue(Continue expression);

}
