//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public class Print(IExpression expr) : IStatement
{
	public IExpression Expr => expr;
	public T Accept<T>(IStatementVisitor<T> visitor) => visitor.VisitPrintStatement(this);
}
