//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public class Return(Token keyword, IExpression value) : IStatement
{
	public Token Keyword => keyword;
	public IExpression Value => value;
	public T Accept<T>(IStatementVisitor<T> visitor) => visitor.VisitReturnStatement(this);
}
