//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public class Var(Token name, IExpression initializer) : IStatement
{
	public Token Name => name;
	public IExpression Initializer => initializer;
	public T Accept<T>(IStatementVisitor<T> visitor) => visitor.VisitVarStatement(this);
}
