//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

using Lox.NET.Expression;

namespace Lox.NET.Statement;

public class While(IExpression condition, IStatement body) : IStatement
{
	public IExpression Condition => condition;
	public IStatement Body => body;
	public T Accept<T>(IStatementVisitor<T> visitor) => visitor.VisitWhileStatement(this);
}
