//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Assign(Token name, IExpression right) : IExpression
{
	public Token Name => name;
	public IExpression Right => right;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitAssign(this);
}
