//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Binary(IExpression left, Token op, IExpression right) : IExpression
{
	public IExpression Left => left;
	public Token Op => op;
	public IExpression Right => right;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitBinary(this);
}
