//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

namespace Lox.NET.Expression;

public class Binary(IExpression left, Token op, IExpression right) : IExpression
{
	T Accept<T>(IVisitor<T> visitor) => visitor.VisitBinary(this);
}
