//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Call(IExpression callee, Token paren, List<IExpression> arguments) : IExpression
{
	public IExpression Callee => callee;
	public Token Paren => paren;
	public List<IExpression> Arguments => arguments;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitCallExpression(this);
}
