//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Get(IExpression obj, Token name) : IExpression
{
	public IExpression Obj => obj;
	public Token Name => name;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitGetExpression(this);
}
