//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Grouping(IExpression expression) : IExpression
{
	public IExpression Expression => expression;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitGrouping(this);
}
