//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

namespace Lox.NET.Expression;

public interface IExpressionVisitor<T>
{
	T VisitTernary(Ternary expression);
	T VisitBinary(Binary expression);
	T VisitGrouping(Grouping expression);
	T VisitLiteral(Literal expression);
	T VisitUnary(Unary expression);
	T VisitVariable(Variable expression);

}
