//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

namespace Lox.NET.Expression;

public interface IExpression
{
	public T Accept<T>(IVisitor<T> visitor);
}
