//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

namespace Lox.NET.Expression;

public interface IExpressionVisitor<T>
{
	T VisitTernaryExpression(Ternary expression);
	T VisitAssignExpression(Assign expression);
	T VisitBinaryExpression(Binary expression);
	T VisitGroupingExpression(Grouping expression);
	T VisitCallExpression(Call expression);
	T VisitLiteralExpression(Literal expression);
	T VisitLogicalExpression(Logical expression);
	T VisitUnaryExpression(Unary expression);
	T VisitVariableExpression(Variable expression);

}
