//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

namespace Lox.NET.Expression;

public interface IVisitor<T>
{
	T VisitBinary(Binary expression);
	T VisitGrouping(Grouping expression);
	T VisitLiteral(Literal expression);
	T VisitUnary(Unary expression);
	T VisitTernary(Ternary expression);
}
