//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

namespace Lox.NET.Expression;

public class Literal(Object val) : IExpression
{
	T Accept<T>(IVisitor<T> visitor) => visitor.VisitLiteral(this);
}
