//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Set(IExpression obj, Token name, IExpression val) : IExpression
{
	public IExpression Obj => obj;
	public Token Name => name;
	public IExpression Val => val;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitSetExpression(this);
}
