//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Super(Token keyword, Token method) : IExpression
{
	public Token Keyword => keyword;
	public Token Method => method;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitSuperExpression(this);
}
