//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

namespace Lox.NET.Expression;

public class Ternary(IExpression condition, Token firstOperatorToken, IExpression ifTrue, Token secondOperatorToken, IExpression ifFalse) : IExpression
{
	public IExpression Condition => condition;
	public Token FirstOperatorToken => firstOperatorToken;
	public IExpression IfTrue => ifTrue;
	public Token SecondOperatorToken => secondOperatorToken;
	public IExpression IfFalse => ifFalse;
	public T Accept<T>(IVisitor<T> visitor) => visitor.VisitTernary(this);
}
