//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class This(Token keyword) : IExpression
{
	public Token Keyword => keyword;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitThisExpression(this);
}
