//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>

namespace Lox.NET.Expression;

public class Unary(Token op, IExpression right) : IExpression
{
	T Accept<T>(IVisitor<T> visitor) => visitor.VisitUnary(this);
}
