//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Unary(Token op, IExpression right) : IExpression
{
	public Token Op => op;
	public IExpression Right => right;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitUnaryExpression(this);
}
