//<auto-generated>
// This code was generated by Tool. Any changes will be erased.
//</auto-generated>


namespace Lox.NET.Expression;

public class Variable(Token name) : IExpression
{
	public Token Name => name;
	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.VisitVariable(this);
}
